import { deleteUser } from '../utils/apiCalls';

export type LoginLang = {
    welcome: string;
    welcomeBack: string,
    workTogether: string,
    partner: string,
    writeUs: string,
    supportedBy: string,
    copyright: string,
    emailAddress: string,
    email: string,
    password: string,
    rememberPassword: string,
    forgotPassword: string,
    enter: string,
    enterYourEmail: string,
    send: string,
    close: string,
    loading: string,
    loginError: string,
}

export type MaintenanceLang = {
    welcome: string;
    welcomeBack: string,
    workTogether: string,
    partner: string,
    writeUs: string,
    supportedBy: string,
    copyright: string,
    emailAddress: string,
    email: string,
    password: string,
    rememberPassword: string,
    forgotPassword: string,
    enter: string,
    enterYourEmail: string,
    send: string,
    close: string,
    loading: string,
}

export type errorLang = {
    title500: string,
    description500: string,
    title404: string,
    title401: string,
    title400: string,
    description404: string,
    description401: string,
    description400: string
    reason1400: string,
    reason2400: string,
    reason1401: string,
    reason2401: string,
    reason1404: string,
    reason2404: string,
    unknownStatus: string,
    back: string,
}

export type MainpageLang = {
    welcome: string,
    logout: string,
    assesmentTool: string,
    dataTool: string,
    managementTool: string,
    alerts: string,
    and: string,
    news: string,
    backToHome: string,
    backToLocalNews: string,
    backToGlobalNews: string,
    backToAdminTools: string,
    backToUserManagementPanel: string,
    backToCreateUserInfo: string,
    backToInterventionsPanel: string,
    security: string,
    personalInfo: string,
}

export type covidTool = {
    companyName: string,
    toolName: string,
    tool: string,
    defaultFilter: string,
    filterSector: string,
    filterGroup: string,
    defaultFilterName: string,
    filterSectorName: string,
    filterGroupName: string,
    defaultCount: string,
    countTotal: string,
    defaultCountName: string,
    countTotalName: string,
    measurement: string,
    positive: string,
    negative: string,
    area: string,
    lineChartTitle: string,
    range: string,
}
export type healthIssuesTool = {
    companyName: string,
    toolName: string,
    tool: string,
    defaultFilter: string,
    filterSector: string,
    filterGroup: string,
    defaultFilterName: string,
    filterSectorName: string,
    filterGroupName: string,
    defaultCount: string,
    countTotal: string,
    defaultCountName: string,
    countTotalName: string,
    measurement: string,
    defaultCovidType: string,
    area: string,
    barChartTitle: string,
    range: string,
}
export type minorInjuriesTool = {
    companyName: string,
    toolName: string,
    tool: string,
    defaultFilter: string,
    filterSector: string,
    filterGroup: string,
    defaultFilterName: string,
    filterSectorName: string,
    filterGroupName: string,
    defaultCount: string,
    countTotal: string,
    defaultCountName: string,
    countTotalName: string,
    measurement: string,
    lineChartTitle: string,
    age: string,
    wage: string,
    activity: string,
    injury: string,
    barChartTitle: string,
    range: string,
}
export type iloToolLang = {
    companyName: string,
    toolName: string,
    tool: string,
    defaultFilter: string,
    filterSector: string,
    filterGroup: string,
    defaultFilterName: string,
    filterSectorName: string,
    filterGroupName: string,
    defaultCount: string,
    countTotal: string,
    defaultCountName: string,
    countTotalName: string,
    measurement: string,
    lineChartTitle: string,
    cases: string,
    age: string,
    wage: string,
    activity: string,
    costCare: string,
    injury: string,
    barChartTitle: string,
    paidCare: string,
    unpaidCare: string,
    nA: string,
    range: string,
    gender: string,
    allowance: string,
    daysAbsence: string,
    overtime: string,
    paidAbsence: string,
}
export type adminToolLang = {
    companyName: string,
    title: string,
    hello: string,
    toolName: string,
    tool: string,
    userManagementPanel: string,
    createUserInfo: string,
    userInfo: string,
    userPermissions: string,
    editUserInfo: string,
    seeUserInfo: string,
    createUserPermissions: string,
    editUserPermissions: string,
    giveSuperUserPermissions: string,
    giveSuperUserPermissionsInfo: string,
    userIsSuperUser: string,
    userIsSuperUserInfo: string,
    baseApps: string,
    selectRole: string,
    reader: string,
    editor: string,
    admin: string,
    notAllowed: string,
    selectSubApp: string,
    selectSubRole: string,
    userSecurity: string,
    userManagementPanelDescription: string,
    interventionsDescription: string,
    updated: string,
    name: string,
    lastName: string,
    email: string,
    telephone: string,
    birthdate: string,
    gender: string,
    select: string,
    country: string,
    address: string,
    nid: string,
    allowedFactories: string,
    add: string,
    addFactory: string,
    search: string,
    searchAndAllow: string,
    male: string,
    female: string,
    password: string,
    confirmPassword: string,
    passwordEmpty: string,
    passwordNotMatch: string,
    passwordRequirements: string,
    telephoneEmpty: string,
    telephoneInvalid: string,
    permissionsFormatError: string,
    save: string,
    saveAndContinue: string,
    edit: string,
    actions: string,
    createUser: string,
    cancel: string,
    close: string,
    delete: string,
    deleteUser: string,
    userDeleteConfirmation: string,
    userDeleteConfirmationDescription: string,
    newUser: string,
    interventions: string,
    interventionsPanel: string,
    newIntervention: string,
    editIntervention: string,
    deleteIntervention: string,
    deleteInterventionConfirmation: string,
    deleteInterventionConfirmationDescription: string,
    factory: string,
    manager: string,
    type: string,
    arrivalTime: string,
    departureTime: string,
    discrepancies: string,
    description: string,
    interventionType: string,
    addPicture: string,
    picture: string,
    date: string,
    reviewSignedBy: string,
    examine: string,
    examineIntervention: string,
    factoryContact: string,
    type: string,
    selectType: string,
    selectFactory: string,
    date: string,
    arrivalTime: string,
    departureTime: string,
    discrepancies: string,
    descriptionEnglish: string,
    descriptionBangla: string,
}
export type alertsNews = {
    name: string,
}
export type lang = {
    auth: {
        login: LoginLang
    },
    maintenance: MaintenanceLang,
    mainpage: mainpageLang;
    notFound: errorLang;
    covidTool: covidTool;
    healthIssuesTool: healthIssuesTool;
    minorInjuriesTool: minorInjuriesTool;
    iloTool: iloTool;
    alertsNews: alertsNews;
    adminTool: adminToolLang;
}
